version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./conf-prod/:/etc/nginx/conf.d/
      - /home/ubuntu/nginx-logs/:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
      - 8088:8088
    networks:
      - gilgeorigoreuda-network

networks:
  gilgeorigoreuda-network:
    external: true